### ISSUE TITLE
Trees Options - Field Item Editor

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#273] opened 2020-05-30 18:51 UTC
# Trees Options - Field Item Editor

### 2. Bulk-Change Tree Type (Example: Bulk-Change Trees to hardwood tree)
> N. 2: could change tree type to money tree too
#### 5. Bulk-Change Money tree uses (Example: Bulk Change Money Tree uses to [value])
> N. 4 & 5: could be useful to get a bunch of item trees

**Comment by Corgano** [comment] 2020-05-31 01:58
Why not bulk remove / replace by ID? you could replace trees with rocks! rocks with trees! Etc.

**Comment by MirayXS** [comment] 2020-05-31 09:53
there aren't search, bulk search or bulk replace as i know

**Comment by Corgano** [comment] 2020-05-31 19:15
Why not suggest adding the feature of bulk remove / replace by ID? you could replace trees with rocks! rocks with trees! Etc. This doesn't just benefit trees.

**Comment by MirayXS** [comment] 2020-05-31 19:16
> Why not suggest adding the feature of bulk remove / replace by ID? you could replace trees with rocks! rocks with trees! Etc. This doesn't just benefit trees.

Good suggestion, if you can you can make an issue with the suggestion :) if not I will make it 4 you

**Comment by Corgano** [comment] 2020-05-31 19:22
IT's functionally synomanious with this though. IT would be functionally a duplicate of this suggestion.

Replace the word "tree" with the word "item" and it would be a literal copy paste. Any solution that applies bulk remove / replace by ID would simultaneously solve this issue by inputting the ID of a tree.

They are the same issue / suggestion differing only in scope.

**Closed** 2020-05-31 22:30 UTC
