### ISSUE TITLE
 bulletin board Art

### ISSUE THREAD

**Issue by ghost** [kwsch/NHSE#619] opened 2023-02-24 21:08 UTC
I was wondering if its possible to be able to save the bulletin board art. 

I have quite a few board art that I love but want to reset my island. I been afraid to because I dont want to lose them. It would be really helpful and appreciated if its possible as a future feature?

**Comment by berichan** [comment] 2023-12-16 21:58
I am closing this as a duplicate of #344 as the two seem to be related

**Closed by berichan** 2023-12-16 21:58 UTC
Labels: enhancement, good issue
