### ISSUE TITLE
Typing items manually in the Edit Map section Error.

### ISSUE THREAD

**Issue by Kayxlicious** [kwsch/NHSE#647] opened 2024-03-07 05:43 UTC
**ISSUE**
When I type in items to search in Map Editor, It does not allow me to type one letter, instead a separate error message comes up. See below:

" The program NHSE. WinForms.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience.
This can be caused by a problem in the program or a deficiency in
Wine. You may want to check
http://www.codeweavers.com/compatibility for tips about running this application. "

Note: I have tried multiple times, the program exits out after it prompts this message.

It is slower for me to find and edit my town, I have to scroll alphabetically to find my items.

Please assist, thank you so much in advance for all you do!

**Comment by Kayxlicious** [comment] 2024-03-07 05:44
<img width="689" alt="Screenshot 2024-03-07 at 12 39 54 AM" src="https://github.com/kwsch/NHSE/assets/23441840/c0529f77-81aa-4241-a707-08e83a051e8d">

**Comment by kwsch** [comment] 2024-03-07 06:21
If you are using Wine, be sure you are using the latest version of it.

NHSE is a Windows Forms application designed to run on Windows operating systems, and without seeing the stacktrace error message, it is impossible to discern what the root cause of your error may be.

**Comment by Kayxlicious** [comment] 2024-03-07 06:24
Thank you. I am using Mac, that is why I am using Wine. Do you have any suggestions to run smoothly on Mac? Is Wine only option? Thank you for your help and reply x

**Comment by kwsch** [comment] 2024-03-07 06:25
Again, without knowing the full error message (show details?) it is impossible to know what is misbehaving. Be sure you are using the latest version of Wine, not something outdated.

**Comment by Kayxlicious** [comment] 2024-03-07 06:25
Thank you !

**Comment by Kayxlicious** [comment] 2024-03-10 04:29
Hi there - I am going to reopen I got the error code. Please see below. Still having issues with Typing in Field Items , program crashed. Have tried multiple downloads from Wine Skin, Crossover etc.

Unhandled exception: page fault on read access to 0x0026262600262626 in 64-bit code (0x000003af6f1620).
Register dump:
 rip:00000003af6f1620 rsp:000000000011c488 rbp:0000000000000000 eflags:00000207 (   - --  I   - -P-C)
 rax:0000000000a93840 rbx:0000000000a8ca50 rcx:0026262600262626 rdx:000000000011c538
 rsi:0026262600262626 rdi:000000000011c538  r8:0000000001c004d8  r9:0000000000000000 r10:0000000000000fe0
 r11:00000001801c5670 r12:0000000010a83100 r13:000000000e7fac08 r14:0000000000a93840 r15:0000000000000400
Stack dump:
0x0000000011c488:  0000000180212d7a 0000000001c004d8
0x0000000011c498:  0000000180238b34 00000000000000f8
0x0000000011c4a8:  000000000385fb40 000000000000003d
0x0000000011c4b8:  0000000000a8ca50 0026262600262626
0x0000000011c4c8:  000000000011c538 00000000060a6b40
0x0000000011c4d8:  00000001801d045d 000000000b895e53
0x0000000011c4e8:  0000000000000000 416312d000000000
0x0000000011c4f8:  0026262600262626 0000000000a8c2a0
0x0000000011c508:  00000001801c56ae 0000000000000000
0x0000000011c518:  0000000000000000 0000000000000000
0x0000000011c528:  0000000000000000 3f80000000000000
0x0000000011c538:  0000000000000000 0000000000000000
Backtrace:
=>0 0x000003af6f1620 _Cbuild+0x376f0() in ucrtbase (0000000000000000)
  1 0x00000180212d7a MonoFixupExe+0x7722a() in libmono-2.0-x86_64 (0000000000000000)
  2 0x000001801d045d MonoFixupExe+0x3490d() in libmono-2.0-x86_64 (0000000000000000)
  3 0x000001801c56ae MonoFixupExe+0x29b5e() in libmono-2.0-x86_64 (0000000000000000)
0x000003af6f1620 ucrtbase+0x81620: cmpw	$0,(%rcx)
Modules:
Module	Address					Debug info	Name (75 modules)
ELF	0000000000001000-000000000000c000	Deferred        <wine-loader>
PE	0000000000400000-00000000004b8000	Deferred        nhse.winforms
PE	0000000003230000-00000000036ac000	Deferred        mscorlib
PE	0000000003960000-0000000003c24000	Deferred        system
PE	0000000003c30000-0000000003cb0000	Deferred        system.drawing
PE	0000000003cb0000-0000000003cb8000	Deferred        accessibility
PE	0000000003de0000-0000000003e06000	Deferred        system.configuration
PE	0000000008670000-0000000008680000	Deferred        i18n
PE	0000000008680000-000000000869a000	Deferred        i18n.west
PE	00000000089d0000-0000000009074000	Deferred        nhse.core
PE	0000000009980000-0000000009a90000	Deferred        system.core
PE	000000000b0c0000-000000000b6c0000	Deferred        nhse.sprites
PE	000000000b810000-000000000b85a000	Deferred        system.design
PE	000000000c240000-000000000c280000	Deferred        mono.security
PE	000000000c280000-000000000c58e000	Deferred        system.xml
PE	0000000010000000-000000001079a000	Deferred        system.windows.forms
PE	00000000453a9000-00000000453b9000	Deferred        libwine.1.0.dylib
ELF	00000000453c1000-00000000453d1000	Deferred        user32.so
ELF	00000000453d9000-00000000453e9000	Deferred        ws2_32.so
ELF	0000000047797000-00000000477af000	Deferred        bcrypt.so
ELF	000000006ae4c000-000000006af20000	Deferred        ntdll.so
PE	000000006b5b5000-000000006b5cd000	Deferred        libobjc-trampolines.dylib
ELF	000000006b669000-000000006b819000	Deferred        win32u<elf>
  \-PE	000000006b670000-000000006b809000	\               win32u
PE	000000006b819000-000000006b8a1000	Deferred        libgmp.10.dylib
PE	000000006ba0b000-000000006bac7000	Deferred        libcxfreetype.6.dylib
ELF	000000006bbb4000-000000006bc64000	Deferred        winemac<elf>
  \-PE	000000006bbc0000-000000006bc50000	\               winemac
PE	000000006be6c000-000000006c074000	Deferred        libgnutls.30.dylib
ELF	000000006d113000-000000006d12b000	Deferred        winecoreaudio.so
PE	0000000078ce7000-0000000078e5f000	Deferred        coreaudio
PE	000000007b000000-000000007b24e000	Deferred        kernelbase
PE	000000007b600000-000000007b65e000	Deferred        kernel32
PE	000000007bf00000-000000007bf1b000	Deferred        menu helper
PE	0000000170000000-000000017009e000	Deferred        ntdll
PE	0000000180000000-000000018045c000	Export          libmono-2.0-x86_64
PE	00000001c69e0000-00000001c72fe000	Deferred        shell32
PE	00000001c8b40000-00000001c8b60000	Deferred        msacm32
PE	00000001c8db0000-00000001c8e47000	Deferred        msvcrt
PE	00000001c92d0000-00000001c92f7000	Deferred        winecoreaudio
PE	00000001ec2b0000-00000001ec2d6000	Deferred        ws2_32
PE	00000001f2230000-00000001f2451000	Deferred        msxml3
PE	00000001fc170000-00000001fc185000	Deferred        fusion
PE	0000000228450000-000000022847b000	Deferred        propsys
PE	0000000231ae0000-0000000231b62000	Deferred        rpcrt4
PE	000000023d820000-000000023d9ec000	Deferred        user32
PE	0000000243540000-00000002435c5000	Deferred        gdiplus
PE	000000024f470000-000000024f48f000	Deferred        mpr
PE	00000002522e0000-0000000252324000	Deferred        oleacc
PE	000000026b4c0000-000000026b53b000	Deferred        gdi32
PE	00000002739c0000-0000000273af6000	Deferred        oleaut32
PE	00000002bb750000-00000002bb88f000	Deferred        comctl32
PE	00000002d4d40000-00000002d4d57000	Deferred        bcrypt
PE	00000002e3540000-00000002e3591000	Deferred        shlwapi
PE	00000002e8f10000-00000002e902b000	Deferred        ole32
PE	00000002f1fa0000-00000002f1fad000	Deferred        version
PE	00000002f7230000-00000002f7265000	Deferred        uxtheme
PE	00000003126f0000-0000000312709000	Deferred        shcore
PE	0000000327020000-0000000327073000	Deferred        combase
PE	000000032a700000-000000032a729000	Deferred        sechost
PE	000000032f9a0000-000000032f9ab000	Deferred        msimg32
PE	0000000330260000-000000033029f000	Deferred        advapi32
PE	0000000330a70000-0000000330a81000	Deferred        uiautomationcore
PE	0000000336850000-000000033687b000	Deferred        mmdevapi
PE	00000003422e0000-000000034237c000	Deferred        urlmon
PE	0000000356770000-00000003567aa000	Deferred        mscoree
PE	0000000361860000-00000003619ec000	Deferred        windowscodecs
PE	00000003a0440000-00000003a04c3000	Deferred        wininet
PE	00000003af670000-00000003af730000	Export          ucrtbase
PE	00000003afd00000-00000003afd1a000	Deferred        imm32
PE	00000003b8f00000-00000003b8fc1000	Deferred        winmm
PE	00000003be590000-00000003be604000	Deferred        dbghelp
PE	00007ff817547000-00007ff817583000	Deferred        libsystem_kernel.dylib
PE	00007ff817581000-00007ff81758d000	Deferred        libsystem_pthread.dylib
PE	00007ff8175ae000-00007ff8175ba000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 winewrapper.exe
	00000024    0     
00000030 services.exe
	00000034    0     
	00000038    0     
	00000044    0     
	00000064    0     
	00000088    0     
	000000a0    0     
	000000cc    0     
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     
	00000054    0     
	00000058    0     
	000000ac    0     
0000005c winedevice.exe
	00000060    0     
	00000068    0     
	0000006c    0     
	00000070    0     
	00000074    0     
	00000078    0     
	0000007c    0     
00000080 plugplay.exe
	00000084    0     
	0000008c    0     
	00000090    0     
	00000094    0     
00000098 svchost.exe
	0000009c    0     
	000000a4    0     
	000000a8    0     
000000b0 explorer.exe
	000000b4    0     
	000000b8    0     
	000000bc    0     
000000c4 rpcss.exe
	000000c8    0     
	000000d4    0     
	000000d8    0     
	000000dc    0     
	000000e0    0     
	000000e4    0     
000000ec (D) Y:\Downloads\NHSE 6\NHSE.WinForms.exe
	000000f0    0 <== 
	000000f4    0     
	000000f8    0     
	000000fc    0     
	00000114    0     
	00000118    0     
00000124 conhost.exe
	00000128    0     
System information:
    Wine build: wine-7.7-8325-gfab1fe5ecef
    Platform: x86_64
    Version: Windows 10
    Host system: Darwin
    Host version: 22.1.0

**Comment by kwsch** [comment] 2024-03-10 06:02
> Wine build: wine-7.7-8325-gfab1fe5ecef

I recommend you update your version of Wine; there are much newer versions available (9.3) that will likely have fixed this issue. I'm pretty sure this is not an issue with NHSE, moreso the implementation that Wine uses to emulate the Windows GUI elements.

**Comment by Kayxlicious** [comment] 2024-03-12 18:38
I updated, here is the new details error:

**Comment by lottehime** [comment] 2024-04-29 01:47
Closing this one due to external layer/emulation issue not internal issue.

**Closed by lottehime** 2024-04-29 01:47 UTC
Labels: bug, invalid
